class_name PartsElf

## The elf: 72 voxels tall, narrow, and pointed at the ears.
##
## THE SILHOUETTE IS "TALL AND NARROW, EARS" and every number here serves it.
## The torso is 12 wide against the human's 20 and the arms are 4 against 6,
## so the body is a column; the head stays a full 16 wide, which makes it read
## as LARGE on a narrow frame rather than as merely small; and the ears put six
## voxels of hard outline outside the skull on each side, which is the one
## feature that survives at 40 m when the width difference has stopped being
## legible.
##
## THE STACK, in model voxels:
##
##     legs   [0, 24)  24
##     pelvis [24, 27)  3
##     torso  [27, 47) 20
##     neck   [47, 50)  3   the bottom three slices of the head part
##     head   [50, 72) 22
##
## The neck is part of the head part, not a bone: a neck bone would be a fifth
## thing to pose for no gain, and putting the neck at the bottom of the head
## part means the head rotates about the BASE of the neck, which is where a
## head-look should pivot anyway.
##
## GENERATED by tools/parts_author/elf.py. Re-run
## `python -m tools.parts_author` after editing the generator. Editing the
## ASCII by hand is legal - say so on this line if you do, so the next
## person knows the generator is behind.


# --- Head ---------------------------------------------------------------------
#
# 28 wide, 3 + 22 tall, 16 deep plus one for the nose. The SKULL is 16 wide and
# occupies columns 6 to 21; the outer six columns on each side are ear, and
# they exist only at z 7 to 10 - an ear is a flat blade on the side of a head,
# not a slab through it.
#
# The ears sweep: six voxels out at eye level, four above that, two at the
# crown, nothing below. That taper is what makes them read as ears rather
# than as handles, and six is the look plan's number: at 40 m the ears are
# the one feature that survives when the width difference has stopped being
# legible, so they are the feature that gets exaggerated.
#
# The bottom three slices are the neck, 8 x 8, and the neck is part of the
# head part rather than a bone: the head rotates about the BASE of the neck,
# which is where a head-look should pivot.

const HEAD := {
	"size": Vector3i(28, 25, 17),
	"anchor": Vector3(14, 0, 9),
	"slices": [
		# y = 0, the neck
		["............................", "............................",
		 "............................", "............................",
		 "............................", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "............................",
		 "............................", "............................",
		 "............................"],
		["............................", "............................",
		 "............................", "............................",
		 "............................", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "............................",
		 "............................", "............................",
		 "............................"],
		["............................", "............................",
		 "............................", "............................",
		 "............................", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "..........SSSSSSSS..........",
		 "..........SSSSSSSS..........", "............................",
		 "............................", "............................",
		 "............................"],
		# y = 3, the chin, stepped in twice
		["............................", "............................",
		 "............................", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "............................",
		 "............................"],
		["............................", "............................",
		 "........SSSSSSSSSSSS........", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", "........SSSSSSSSSSSS........",
		 "............................"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 8, the mouth
		["............................", "........SSMMMMMMMMSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 11, the nose
		[".............SS.............", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		[".............SS.............", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 13, eyes, the iris rows
		[".............SS.............", "........WWEESSSSEEWW........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 14, the ears, six voxels out
		["............................", "........WWEESSSSEEWW........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........WWWWSSSSWWWW........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........WWWWSSSSWWWW........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 17, the brows
		["............................", "........ssssSSSSssss........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSSSSSSSSSSSS", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 18, the ears sweep in
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "..SSSSSSSSSSSSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSSSSSSSSSSSS..", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "..SSSSSSSSSSSSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSSSSSSSSSSSS..", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "....SSSSSSSSSSSSSSSSSSSS....",
		 "....SSSSSSSSSSSSSSSSSSSS....", "....SSSSSSSSSSSSSSSSSSSS....",
		 "....SSSSSSSSSSSSSSSSSSSS....", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "....SSSSSSSSSSSSSSSSSSSS....",
		 "....SSSSSSSSSSSSSSSSSSSS....", "....SSSSSSSSSSSSSSSSSSSS....",
		 "....SSSSSSSSSSSSSSSSSSSS....", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		["............................", "........SSSSSSSSSSSS........",
		 ".......SSSSSSSSSSSSSS.......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", "......SSSSSSSSSSSSSSSS......",
		 "......SSSSSSSSSSSSSSSS......", ".......SSSSSSSSSSSSSS.......",
		 "........SSSSSSSSSSSS........"],
		# y = 23, the crown, stepped in
		["............................", "............................",
		 "............................", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "........SSSSSSSSSSSS........",
		 "........SSSSSSSSSSSS........", "............................",
		 "............................"],
		["............................", "............................",
		 "........SSSSSSSSSSSS........", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", ".......SSSSSSSSSSSSSS.......",
		 ".......SSSSSSSSSSSSSS.......", "........SSSSSSSSSSSS........",
		 "............................"],
	],
}


# --- Torso --------------------------------------------------------------------
#
# 12 wide, 20 tall, 8 deep. A column, against the human's 20 x 11, with the
# same stepped shoulders and the same belt. The head stays a full 16 wide on
# it, which makes it read as LARGE on a narrow frame rather than as merely
# small.

const TORSO := {
	"size": Vector3i(12, 20, 8),
	"anchor": Vector3(6, 0, 4),
	"slices": [
		# y = 0, the belt
		["BBBBBXXBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB",
		 "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB"],
		["BBBBBXXBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB",
		 "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB", "BBBBBBBBBBBB"],
		# y = 2, the tunic
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		["CCCCCccCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC",
		 "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC", "CCCCCCCCCCCC"],
		# y = 18, the shoulders step in
		[".CCCccccCCC.", ".CCCCCCCCCC.", ".CCCCCCCCCC.", ".CCCCCCCCCC.",
		 ".CCCCCCCCCC.", ".CCCCCCCCCC.", ".CCCCCCCCCC.", ".CCCCCCCCCC."],
		["............", "..CccccccC..", "..CCCCCCCC..", "..CCCCCCCC..",
		 "..CCCCCCCC..", "..CCCCCCCC..", "..CCCCCCCC..", "............"],
	],
}


# --- Pelvis -------------------------------------------------------------------
#
# 12 wide, 3 tall, 8 deep. The three voxels the elf's stack does not spend on
# anything else.

const PELVIS := {
	"size": Vector3i(12, 3, 8),
	"anchor": Vector3(6, 0, 4),
	"slices": [
		["cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc",
		 "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc"],
		["cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc",
		 "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc"],
		["cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc",
		 "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc"],
	],
}


# --- Leg ----------------------------------------------------------------------
#
# 5 wide, 24 tall, 5 deep - the longest legs in the game - in a 7 x 7 boot.
# The anchor is the top centre of the trouser leg. `leg_w` in the race table
# is 6, one more than the trouser, so the boots touch rather than overlap.

const LEG := {
	"size": Vector3i(7, 24, 7),
	"anchor": Vector3(3.5, 24, 4.5),
	"slices": [
		# y = 0, the boot
		["LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL",
		 "LLLLLLL"],
		["LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL",
		 "LLLLLLL"],
		["LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL",
		 "LLLLLLL"],
		["LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL", "LLLLLLL",
		 "LLLLLLL"],
		# y = 4, the trouser leg, five by five
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
		[".......", ".......", ".ccccc.", ".ccccc.", ".ccccc.", ".ccccc.",
		 ".ccccc."],
	],
}


# --- Arm ----------------------------------------------------------------------
#
# 4 wide, 24 long, 4 deep, with a 6 x 6 hand. The thinnest arm in the game on
# the longest reach; `arm_w` is the hand's 6, so the hand hangs flush with the
# torso and the sleeve has a voxel of daylight at the armpit.

const ARM := {
	"size": Vector3i(6, 24, 6),
	"anchor": Vector3(3, 24, 3),
	"slices": [
		# y = 0, the hand, six by six
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		["ssssss", "ssssss", "ssssss", "ssssss", "ssssss", "ssssss"],
		# y = 6, the forearm
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		["......", ".SSSS.", ".SSSS.", ".SSSS.", ".SSSS.", "......"],
		# y = 15, the cuff
		["......", ".cccc.", ".cccc.", ".cccc.", ".cccc.", "......"],
		# y = 16, the sleeve
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
		["......", ".CCCC.", ".CCCC.", ".CCCC.", ".CCCC.", "......"],
	],
}


## Every part in this set, by the name a bone table refers to it with.
const PARTS := {
	"head": HEAD,
	"torso": TORSO,
	"pelvis": PELVIS,
	"leg": LEG,
	"arm": ARM,
}
