class_name PartsCritter

## A four-legged thing the size of a large dog.
##
## IT EXISTS TO FAIL LOUDLY IF ANY OF THIS IS SECRETLY HUMANOID. It has no
## `torso`, no `hips`, no arms and four legs, so every place in the pipeline
## that quietly assumed a two-legged skeleton - the mesher, the rig, the chain
## rule, the animator - either works on it or does not. Nothing else in this
## plan could have found those assumptions, because everything else in this
## plan is a person.
##
## GALLERY ONLY. No AI, no scene, no spawning, no CharacterDef. It is a model
## that walks in a strip, and it is what the first-enemy plan starts from.
##
## Shoulder height is 22 voxels, 0.69 m, which is a big dog. The body is
## twenty-eight voxels long, so it is longer than it is tall by two to one -
## the proportion that makes a quadruped read as a quadruped rather than as a
## person on all fours.
##
## SCALED EXACTLY x2 FROM CHARACTER V1 when the model voxel halved. It is a
## test rig, and the only thing that matters about its shape is that it is the
## same shape it was - so every v1 voxel became eight and nothing else
## changed. It has no chamfers and no Deco; the first-enemy plan draws the
## first real animal.
##
## GENERATED by tools/parts_author/critter.py. Re-run
## `python -m tools.parts_author` after editing the generator. Editing the
## ASCII by hand is legal - say so on this line if you do, so the next
## person knows the generator is behind.


# --- Body ---------------------------------------------------------------------
#
# 12 wide, 12 tall, 28 long. The anchor is at the middle of its length and the
# bottom of its height, so the four leg sockets hang from it symmetrically and
# the whole animal sits on top of its legs.

const BODY := {
	"size": Vector3i(12, 12, 28),
	"anchor": Vector3(6, 0, 14),
	"slices": [
		["............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "............", "............"],
		["............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "............", "............"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "............", "............"],
		["............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "............", "............"],
	],
}


# --- Head ---------------------------------------------------------------------
#
# 12 wide, 12 tall, 12 of skull plus 6 of snout. The anchor is at the BACK of
# the head - z 18 - so the head grows forward from the neck joint, which is
# where a quadruped's head hangs from.

const HEAD := {
	"size": Vector3i(12, 12, 18),
	"anchor": Vector3(6, 0, 18),
	"slices": [
		["....TTTT....", "....TTTT....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["....TTTT....", "....TTTT....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["....SSSS....", "....SSSS....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["....SSSS....", "....SSSS....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["....SSSS....", "....SSSS....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["....SSSS....", "....SSSS....", "....SSSS....", "....SSSS....",
		 "....SSSS....", "....SSSS....", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "SSWWEESSEESS", "SSWWEESSEESS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "SSWWEESSEESS", "SSWWEESSEESS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "HHSSSSSSSSHH", "HHSSSSSSSSHH",
		 "HHSSSSSSSSHH", "HHSSSSSSSSHH", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
		["............", "............", "............", "............",
		 "............", "............", "HHSSSSSSSSHH", "HHSSSSSSSSHH",
		 "HHSSSSSSSSHH", "HHSSSSSSSSHH", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS", "SSSSSSSSSSSS",
		 "SSSSSSSSSSSS", "SSSSSSSSSSSS"],
	],
}


# --- Leg ----------------------------------------------------------------------
#
# 4 x 10 x 4, anchored at the TOP so it swings from the shoulder, exactly as a
# humanoid leg does. Authored once and used four times: the gait table decides
# which of them are in phase, not the geometry.

const LEG := {
	"size": Vector3i(4, 10, 4),
	"anchor": Vector3(2, 10, 2),
	"slices": [
		["TTTT", "TTTT", "SSSS", "SSSS"],
		["TTTT", "TTTT", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS"],
	],
}


# --- Tail ---------------------------------------------------------------------
#
# Two segments on the SAME generic chain rule the lizardfolk uses. That is half
# the point of building this animal: if the chain rule had quietly assumed
# three links or a humanoid parent, this is where it would show.

const TAIL_1 := {
	"size": Vector3i(4, 4, 8),
	"anchor": Vector3(2, 0, 0),
	"slices": [
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS"],
	],
}


const TAIL_2 := {
	"size": Vector3i(4, 4, 6),
	"anchor": Vector3(2, 0, 0),
	"slices": [
		["SSSS", "SSSS", "ssss", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "ssss", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "ssss", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "ssss", "ssss", "ssss", "ssss"],
	],
}


## Every part in this set, by the name a bone table refers to it with.
const PARTS := {
	"body": BODY,
	"head": HEAD,
	"leg": LEG,
	"tail_1": TAIL_1,
	"tail_2": TAIL_2,
}


## Model voxels, for the tables below.
const V := VoxelModel.VOXEL_M


## The critter's dimension table, in the shape Races.dims() returns.
##
## `gait` is the only field that is not a measurement, and it is the field this
## whole animal exists to exercise: it names an entry in Animator.RIG_SHAPES,
## which says which bones are legs and which of them share a phase.
const DIMS := {
	"name": "critter",
	"total": 22, "legs": 10, "torso": 12, "head": 12,
	"torso_w": 12, "torso_d": 12, "head_w": 12, "head_d": 18,
	"leg_w": 4, "arm_len": 0, "arm_w": 0,
	"gait": "trot",
	"lean_deg": 0.0,
	"silhouette": "long, low and four-legged",
}


## Bones and sockets, in the shape Races.bone_table() returns.
##
## NO `torso`, NO `hips`, NO ARMS. Written out rather than derived, because
## Races.bone_table() derives a HUMANOID from a race table and this is the
## thing that proves it does not have to be the only shape - a quadruped whose
## bone table came out of the same generator would not be evidence of anything.
static func bone_table() -> Array:
	var leg_x := 3.0
	var leg_z := 10.0
	return [
		{"name": "body", "parent": "", "rest": Vector3(0, 10, 0) * V, "part": "body"},
		{"name": "head", "parent": "body", "rest": Vector3(0, 4, -14) * V, "part": "head"},
		{"name": "leg_fr", "parent": "body", "rest": Vector3(leg_x, 0, -leg_z) * V, "part": "leg"},
		{"name": "leg_fl", "parent": "body", "rest": Vector3(-leg_x, 0, -leg_z) * V,
			"part": "leg", "mirror": true},
		{"name": "leg_br", "parent": "body", "rest": Vector3(leg_x, 0, leg_z) * V, "part": "leg"},
		{"name": "leg_bl", "parent": "body", "rest": Vector3(-leg_x, 0, leg_z) * V,
			"part": "leg", "mirror": true},
		{"name": "tail_1", "parent": "body", "rest": Vector3(0, 8, 14) * V, "part": "tail_1"},
		{"name": "tail_2", "parent": "tail_1", "rest": Vector3(0, 0, 8) * V, "part": "tail_2"},
		# One socket, because the rule is that sockets are not a humanoid idea.
		# A pack, a saddle, a collar: whatever the first-enemy plan wants, the
		# machinery is the same machinery.
		{"name": "back", "parent": "body", "rest": Vector3(0, 12, 0) * V, "socket": true},
	]


## A palette for it. Not a race, so it has no entry in Races - and that is the
## point: the mesher takes any slot table at all.
static func palette() -> Dictionary:
	var hide := Color.html("#6B5B45").srgb_to_linear()
	return {
		VoxelModel.SKIN: hide,
		VoxelModel.SKIN_SHADED: Color(hide.r * 0.8, hide.g * 0.8, hide.b * 0.8),
		VoxelModel.HAIR: Color.html("#3A3028").srgb_to_linear(),
		VoxelModel.IRIS: Color.html("#C9A227").srgb_to_linear(),
		VoxelModel.EYE_WHITE: Color.html("#F4F0E8").srgb_to_linear(),
		VoxelModel.MOUTH: Color.html("#3A2A22").srgb_to_linear(),
		VoxelModel.CLOTH: hide,
		VoxelModel.CLOTH_DARK: hide,
		VoxelModel.LEATHER: Color.html("#3A2A1E").srgb_to_linear(),
		VoxelModel.BELT: Color.html("#5A4632").srgb_to_linear(),
		VoxelModel.TOOTH: Color.html("#EDE6D4").srgb_to_linear(),
		VoxelModel.METAL: Color.html("#9A9FA6").srgb_to_linear(),
		VoxelModel.WOOD: Color.html("#7A5230").srgb_to_linear(),
	}
