class_name PartsHuman

## The stocky human, voxel by voxel, at 1/16 of a block.
##
## Read VoxelModel's class docstring before editing anything here. In short:
## slices run bottom to top, rows inside a slice run front (-Z) to back, and
## the first character of a row is the left of the picture as you look at the
## character's face. Every character is a slot, never a colour.
##
## THE STACK, from the race table, in model voxels:
##
##     legs   [0, 16)  16   boots at the bottom, trousers above
##     pelvis [16, 22)  6   the six voxels the stack does not otherwise spend
##     torso  [22, 42) 20   tunic, belt on its bottom rows
##     head   [42, 64) 22   eyes at 52-55, which is 1.68 m
##
## The arms hang from a shoulder at 41 and are 20 long, so the hands finish at
## the hips. Nothing here is a number `player.gd` may read - hard rule 3.
##
## THIS IS THE REFERENCE. Square stepped shoulders, a head a third of the
## height, big hands and boots, no neck: the look plan's "stocky", and the
## shape every other race is measured against in the silhouette sheets.
##
## GENERATED by tools/parts_author/human.py. Re-run
## `python -m tools.parts_author` after editing the generator. Editing the
## ASCII by hand is legal - say so on this line if you do, so the next
## person knows the generator is behind.


# --- Head ---------------------------------------------------------------------
#
# 18 wide, 22 tall, 16 deep PLUS ONE for the nose. The skull occupies z 1..16
# and the anchor sits at its centre, z = 9, not at the middle of the
# seventeen.
#
# THE HEAD IS A THIRD OF THE CHARACTER. 22 of 64 voxels, which is the Cube
# World read the look plan asks for, kept on the stocky side of it. The
# vertical edges are chamfered two voxels so the head is an octagon from
# above, and the jaw and the crown step in - rule 4 of the look plan: forms are
# stepped and chamfered, never rounded.
#
# THE FACE IS THE WHOLE POINT OF THE FINER VOXEL. Two 4 x 4 eyes, each a white
# with a 2 x 2 iris set low and inboard so the character looks at you rather
# than past you; a one-row brow over each; a 2 x 3 nose one voxel proud; an
# 8-wide mouth. At the game's 75 degree FOV on a 720-line viewport a 4 x 4 eye
# is about five pixels across at 15 m, which is a face and not a smudge.

const HEAD := {
	"size": Vector3i(18, 22, 17),
	"anchor": Vector3(9, 0, 9),
	"slices": [
		# y = 0, the chin, stepped in twice
		["..................", "..................", "..................",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..................", ".................."],
		["..................", "..................", "..SSSSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 "..SSSSSSSSSSSSSS..", ".................."],
		# y = 2, the jaw at full width
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 5, the mouth
		["..................", "..SSSMMMMMMMMSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 8, the nose - the only slices with anything at z = 0
		["........SS........", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["........SS........", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 10, eyes, the iris rows
		["........SS........", "..SWWEESSSSEEWWS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SWWEESSSSEEWWS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 12, eyes, the upper rows
		["..................", "..SWWWWSSSSWWWWS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SWWWWSSSSWWWWS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 14, the brows
		["..................", "..sssssSSSSsssss..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		["..................", "..SSSSSSSSSSSSSS..", ".SSSSSSSSSSSSSSSS.",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSSSS",
		 ".SSSSSSSSSSSSSSSS.", "..SSSSSSSSSSSSSS.."],
		# y = 20, the crown, stepped in
		["..................", "..................", "..................",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..", "..SSSSSSSSSSSSSS..",
		 "..................", ".................."],
		["..................", "..................", "..SSSSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSSSS.",
		 "..SSSSSSSSSSSSSS..", ".................."],
	],
}


# --- Torso --------------------------------------------------------------------
#
# 20 wide, 20 tall, 11 deep. Square shoulders - that IS the human silhouette,
# and it is the reference every other race is separated from - but STEPPED:
# the top two rows inset by one and then two, so the shoulder is a ziggurat
# profile and not a box. Belt on the bottom two rows with a buckle, and a
# stepped V collar on the front, which is the one piece of ornament a tunic
# gets.
#
# The outfit is baked in rather than being a separate part, because the torso
# slot belongs to the gear plan and v1 has one outfit per race.

const TORSO := {
	"size": Vector3i(20, 20, 11),
	"anchor": Vector3(10, 0, 5.5),
	"slices": [
		# y = 0, the belt, buckle on the front
		["BBBBBBBBXXXXBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB"],
		["BBBBBBBBXXXXBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB"],
		# y = 2, the tunic
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		# y = 16, the collar begins
		["CCCCCCCCCccCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCccccCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		# y = 18, the shoulders step in
		[".CCCCCCccccccCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC."],
		["....................", "..CCCCccccccccCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "...................."],
	],
}


# --- Pelvis -------------------------------------------------------------------
#
# 20 wide, 6 tall, 11 deep, in trousers. `hips` is the root of the rig and
# every bone must have a part; this is its part, and it is where the stack's
# six spare voxels go. See the note in races.gd.

const PELVIS := {
	"size": Vector3i(20, 6, 11),
	"anchor": Vector3(10, 0, 5.5),
	"slices": [
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
	],
}


# --- Leg ----------------------------------------------------------------------
#
# 7 wide, 16 tall, 7 deep, in a 9 x 9 boot that is one voxel wider on each
# side and two deeper at the toe. Authored ONCE, for the right leg; the left
# is this mirrored, which is why the two can never drift apart.
#
# The anchor is the TOP centre of the trouser leg, `(4.5, 16, 5.5)`, because a
# leg swings from the hip and not from the ankle. The race table's `leg_w` is
# 8, one more than the trouser, so the two boots touch at the centre line
# instead of sharing a voxel.

const LEG := {
	"size": Vector3i(9, 16, 9),
	"anchor": Vector3(4.5, 16, 5.5),
	"slices": [
		# y = 0, the boot, nine wide and nine deep
		["LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL",
		 "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL"],
		["LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL",
		 "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL"],
		["LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL",
		 "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL"],
		["LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL",
		 "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL", "LLLLLLLLL"],
		# y = 4, the trouser leg, seven by seven
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
		[".........", ".........", ".ccccccc.", ".ccccccc.", ".ccccccc.",
		 ".ccccccc.", ".ccccccc.", ".ccccccc.", ".ccccccc."],
	],
}


# --- Arm ----------------------------------------------------------------------
#
# 6 wide, 20 long, 6 deep, hanging from the shoulder, with an 8 x 8 hand on the
# bottom six rows - one voxel wider all round than the sleeve, which is what
# makes a hand read as a hand at 15 m. Sleeve on the top seven, a dark cuff,
# bare forearm, and the hand in shaded skin so there is a visible wrist on a
# limb that is otherwise one column. Authored for the right arm and mirrored
# for the left.
#
# The race table's `arm_w` is 8 - the hand's width, not the sleeve's - so the
# arm hangs with the hand flush against the torso and a voxel of daylight at
# the armpit.

const ARM := {
	"size": Vector3i(8, 20, 8),
	"anchor": Vector3(4, 20, 4),
	"slices": [
		# y = 0, the hand, eight by eight
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		# y = 6, the forearm
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		# y = 12, the cuff
		["........", ".cccccc.", ".cccccc.", ".cccccc.", ".cccccc.", ".cccccc.",
		 ".cccccc.", "........"],
		# y = 13, the sleeve
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
	],
}


## Every part in this set, by the name a bone table refers to it with.
const PARTS := {
	"head": HEAD,
	"torso": TORSO,
	"pelvis": PELVIS,
	"leg": LEG,
	"arm": ARM,
}
