class_name PartsLizardfolk

## The lizardfolk: a snout in front, a tail behind, and leaning eight degrees
## into both.
##
## THE SILHOUETTE IS "TAIL, CREST, SNOUT" and it is the only one of the four
## that is made of things sticking OUT rather than of overall proportion. The
## body is the human's - same 20 x 11 torso, same 20-voxel arms - which is
## deliberate: if the lizardfolk had a distinct build as well, the silhouette
## test would not be able to tell which feature was doing the work.
##
## THE STACK, in model voxels:
##
##     legs   [0, 18)  18
##     pelvis [18, 22)  4
##     torso  [22, 42) 20
##     head   [42, 60) 18
##
## The 8 degree forward lean is baked into the HIPS REST POSE (see Rig.build),
## not applied by the animator, so it survives every pose and the animator
## never learns that one race stands differently from the others.
##
## GENERATED by tools/parts_author/lizardfolk.py. Re-run
## `python -m tools.parts_author` after editing the generator. Editing the
## ASCII by hand is legal - say so on this line if you do, so the next
## person knows the generator is behind.


# --- Head ---------------------------------------------------------------------
#
# 16 wide, 18 tall, and 24 DEEP: a 16-deep skull at z 8 to 23 with an 8-voxel
# snout in front of it at z 0 to 7. The snout is eight wide and eight tall,
# not sixteen, so the head reads as a wedge from above and as a muzzle from
# the side, and its own edges are chamfered so it is a stepped block rather
# than a box.
#
# The eyes sit on the front of the SKULL at z = 8, above the snout, which is
# where a reptile's are. Teeth on the underside of the snout in the `T` slot,
# a mouth line the whole way round it, and nostrils on top.

const HEAD := {
	"size": Vector3i(16, 18, 24),
	"anchor": Vector3(8, 0, 16),
	"slices": [
		# y = 0, the underside of the jaw
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "................",
		 "..SSSSSSSSSSSS..", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS..", "................"],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		# y = 4, the snout begins - and its teeth
		[".....TTTTTT.....", "....TTTTTTTT....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		[".....SSSSSS.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		# y = 6, the mouth line, round the snout
		[".....MMMMMM.....", "....MSSSSSSM....", "....MSSSSSSM....",
		 "....MSSSSSSM....", "....MSSSSSSM....", "....MSSSSSSM....",
		 "....MSSSSSSM....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		[".....SSSSSS.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		[".....SSSSSS.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		[".....SSSSSS.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		[".....SSSSSS.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		# y = 11, the top of the snout, with nostrils
		[".....ssSSss.....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", "....SSSSSSSS....", "....SSSSSSSS....",
		 "....SSSSSSSS....", ".....SSSSSS.....", "..SSSSSSSSSSSS..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		# y = 12, eyes on the front of the skull, above the snout
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..WWEESSSSEEWW..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..WWEESSSSEEWW..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..WWWWSSSSWWWW..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "..WWWWSSSSWWWW..",
		 ".SSSSSSSSSSSSSS.", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS", "SSSSSSSSSSSSSSSS",
		 "SSSSSSSSSSSSSSSS", ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS.."],
		# y = 16, the brow ridge, and the crown
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "................",
		 "................", "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..",
		 "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..",
		 "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..",
		 "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..", "..SSSSSSSSSSSS..",
		 "..SSSSSSSSSSSS..", "................", "................"],
		["................", "................", "................",
		 "................", "................", "................",
		 "................", "................", "................",
		 "..SSSSSSSSSSSS..", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.", ".SSSSSSSSSSSSSS.",
		 ".SSSSSSSSSSSSSS.", "..SSSSSSSSSSSS..", "................"],
	],
}


# --- Torso --------------------------------------------------------------------
#
# 20 wide, 20 tall, 11 deep - THE HUMAN'S TORSO, stepped shoulders and all,
# with a sash across the front instead of a collar. Deliberate: if the
# lizardfolk had a distinct build as well as a snout, a crest and a tail, the
# silhouette test would not be able to tell which feature was doing the
# work.

const TORSO := {
	"size": Vector3i(20, 20, 11),
	"anchor": Vector3(10, 0, 5.5),
	"slices": [
		# y = 0, the belt, buckle on the front
		["BBBBBBBBXXXXBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB"],
		["BBBBBBBBXXXXBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB",
		 "BBBBBBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBBBBBB"],
		# y = 2, the tunic, with a sash across it
		["CCCCCCCCCCCCCcccCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCCcccCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCCcccCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCCcccCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCcccCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCCcccCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCCcccCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCCcccCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCcccCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCCcccCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCCcccCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCCcccCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCcccCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCCcccCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCCcccCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		["CCcccCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC",
		 "CCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCC"],
		# y = 18, the shoulders step in
		[".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC.",
		 ".CCCCCCCCCCCCCCCCCC.", ".CCCCCCCCCCCCCCCCCC."],
		["....................", "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..", "..CCCCCCCCCCCCCCCC..",
		 "..CCCCCCCCCCCCCCCC..", "...................."],
	],
}


# --- Pelvis -------------------------------------------------------------------
#
# 20 wide, 4 tall, 11 deep. The tail's first link hangs off the back of it.

const PELVIS := {
	"size": Vector3i(20, 4, 11),
	"anchor": Vector3(10, 0, 5.5),
	"slices": [
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
		["cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc", "cccccccccccccccccccc",
		 "cccccccccccccccccccc", "cccccccccccccccccccc"],
	],
}


# --- Leg ----------------------------------------------------------------------
#
# 7 wide, 18 tall, 7 deep with a foot two voxels longer at the toe. Barefoot,
# with three claws at the toes - the one race that does not wear boots. Its
# `leg_w` is the human's 8 so the two feet touch rather than overlap.

const LEG := {
	"size": Vector3i(7, 18, 9),
	"anchor": Vector3(3.5, 18, 5.5),
	"slices": [
		# y = 0, the foot, bare, with claws at the toes
		["TSSTSST", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		["SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		# y = 2, the shin
		[".......", ".......", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		[".......", ".......", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		[".......", ".......", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		[".......", ".......", "SSSSSSS", "SSSSSSS", "SSSSSSS", "SSSSSSS",
		 "SSSSSSS", "SSSSSSS", "SSSSSSS"],
		# y = 6, the trouser leg
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
		[".......", ".......", "ccccccc", "ccccccc", "ccccccc", "ccccccc",
		 "ccccccc", "ccccccc", "ccccccc"],
	],
}


# --- Arm ----------------------------------------------------------------------
#
# The human's arm, with claws on the fingertips.

const ARM := {
	"size": Vector3i(8, 20, 8),
	"anchor": Vector3(4, 20, 4),
	"slices": [
		# y = 0, the hand, with claws
		["sTsTssTs", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		["ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss", "ssssssss",
		 "ssssssss", "ssssssss"],
		# y = 6, the forearm
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.", ".SSSSSS.",
		 ".SSSSSS.", "........"],
		["........", ".cccccc.", ".cccccc.", ".cccccc.", ".cccccc.", ".cccccc.",
		 ".cccccc.", "........"],
		# y = 13, the sleeve
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
		["........", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.", ".CCCCCC.",
		 ".CCCCCC.", "........"],
	],
}


# --- Tail ---------------------------------------------------------------------
#
# Three segments, 10 + 10 + 8 = 28 voxels, tapering: 6 x 6, then 4 x 4, then
# 4 x 4 with a shaded tip. Each is anchored at its FRONT face so it grows
# backward along +Z from the bone that carries it, and each bone's rest
# offset is the previous segment's length - so the chain is continuous by
# construction rather than by three numbers agreeing. The thinner links are
# anchored a voxel up so they sit on the centre line of the thick one.
#
# The animator finds these by name alone (`tail_1..n`) and knows nothing
# about lizards. The critter uses the same rule.

const TAIL_1 := {
	"size": Vector3i(6, 6, 10),
	"anchor": Vector3(3, 0, 0),
	"slices": [
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
		["SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS", "SSSSSS",
		 "SSSSSS", "SSSSSS", "SSSSSS"],
	],
}


const TAIL_2 := {
	"size": Vector3i(4, 4, 10),
	"anchor": Vector3(2, -1, 0),
	"slices": [
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS",
		 "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS",
		 "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS",
		 "SSSS"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "SSSS",
		 "SSSS"],
	],
}


const TAIL_3 := {
	"size": Vector3i(4, 4, 8),
	"anchor": Vector3(2, -1, 0),
	"slices": [
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "ssss", "ssss", "ssss"],
		["SSSS", "SSSS", "SSSS", "SSSS", "SSSS", "ssss", "ssss", "ssss"],
	],
}


## Every part in this set, by the name a bone table refers to it with.
const PARTS := {
	"head": HEAD,
	"torso": TORSO,
	"pelvis": PELVIS,
	"leg": LEG,
	"arm": ARM,
	"tail_1": TAIL_1,
	"tail_2": TAIL_2,
	"tail_3": TAIL_3,
}
